name: Deploy to Prod

on:
   push:
      branches:
         - master

jobs:
   deploy:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout code
           uses: actions/checkout@master

         - name: Install Nodejs
           run: npm ci

         - name: Build
           run: npm run build

         - name: Copy files to server
           run: cd build && rsync -e "ssh -p ${{ secrets.PORT }} -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/${{ secrets.USERNAME }}/elenivan.ru/htdocs/currency
